[features]
seeds = false
skip-lint = false
[programs.devnet]
openmscp = "HpphDK8HgBUAs8zztpEJiwxX2pmwi8qmQpugRhuiwf3x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./tests/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
