[features]
seeds = false
skip-lint = false
[programs.localnet]
mscp_social = "HpphDK8HgBUAs8zztpEJiwxX2pmwi8qmQpugRhuiwf3x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/justin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
